image: alpine

stages:
  - live


deploy_live:
  stage: live
  environment:
    name: Live
    url: http://139.59.14.215
  script:
    - apk add openssh sshpass openrc zip
    - zip -r ASKCTM$(date "+%b_%d_%Y_%H_%M_%S").zip .
    - sshpass -e scp -o stricthostkeychecking=no *.zip root@139.59.14.215:/var/www/html/.
    - sshpass -e ssh -o stricthostkeychecking=no root@139.59.14.215 "cd /var/www/html/ && unzip -o *.zip && chmod -R 755 . && mv *.zip OLD/"
    - rm *.zip

  only:
    - master
